### ISSUE TITLE
v0.0 (pre-release)

### ISSUE THREAD

**Issue by elf-pavlik** [valueflows/valueflows#150]
Issue to track work on releasing v0.1 in Sep 2016

Since we have issues across multiple repositories we can't use Milestone feature easily. We can make a checklist here with issues we want to resolve for that release. Let's also try to release new version each month no matter how many improvements we make. I will also use this issue as reference for tracking time dedicated to this release but not put towards any other existing issue.

Proposed issues:

v0.0
- [ ] [Core vf model](https://github.com/valueflows/valueflows/issues/147)
- [ ] [Use cases to cover decision on event vs resource model](https://github.com/valueflows/process/issues/21)
- [ ] [stock proposal](https://github.com/valueflows/resource/pull/41)
- [ ] [Product vs. Service](https://github.com/valueflows/resource/issues/15)
- [ ] [Measurements: Quantities, Dimensions, Units](https://github.com/valueflows/resource/issues/3)
- [ ] [Event types as subclasses or types or ???](https://github.com/valueflows/valueflows/issues/124)
- ...

possibly postpone to v0.1
- [ ] [defining Transportation](https://github.com/valueflows/process/issues/9)
- [ ] [modeling 'Usage' as vf:Resource (similar to vf:Service)](https://github.com/valueflows/resource/issues/29)
- [ ] [YAML examples for vf:underlyingResource](https://github.com/valueflows/resource/issues/31)
- [ ] [timeline based stocks (availability?) for Usage and Services](https://github.com/valueflows/resource/issues/51)
- [ ] ['orphan' work events](https://github.com/valueflows/process/issues/22)
- [ ] [start & end events for usage & work (similar to load & unload) in transportation](https://github.com/valueflows/process/issues/23)
- [ ] [existing resource vs. planned resource](https://github.com/valueflows/resource/issues/14)
- ...

From Lynn, recommended new issues for 0.0 list:
- [ ] [naming of IPOEvent](https://github.com/valueflows/valueflows/issues/155)
- [ ] [modeling usage](https://github.com/valueflows/valueflows/issues/156)

**Comment by fosterlynn** [comment]
:+1: release!!

**Comment by elf-pavlik** [comment]
I would like to propose to focus on defining *vf:UsageResource*, *vf:ServiceResource* and *vf:WorkResource*. First as input/output of *vf:Process* and than as used in *vf:Intent* and *vf:Transfer*. They seem not clearly supported by REA and NRP seems to propose certain extension to support them just with events but without the resources.

**Comment by bhaugen** [comment]
> They seem not clearly supported by REA 

This will often be the case. REA is deliberately minimal. Ontologies can be defined with different levels of detail and extension for different purposes. REA is a minimal domain ontology where the goal is to define the concepts and relationships in a domain: originally accounting, eventually, economic relationships. It is not intended to be an operational ontology or a specification for software. Those are exercises for the student.

> and NRP seems to propose certain extension to support them just with events but without the resources.

NRP was a prototype that handled the use cases presented to it in participatory action research engagements. (To borrow a phrase from @coopchange ). Those use cases did not include the scheduling and allocation of time-based resources. I did that once before in a skunkworks project in 1996, and remember some of it, but no longer have access to the code or documentation. So I sorta remember how we did it, but am probably fuzzy on some details. I have tried to inject what I remember into the discussions of time-based resources.

But the upshot is that neither REA nor NRP will provide any help in some VF use cases.

**Comment by elf-pavlik** [comment]
I would like to suggest approach we already discussed in on of last hangouts:
* we start with [Planning with the vf:Vocabulary](https://github.com/valueflows/process/issues/18) for example creating something to offer as charity like in https://github.com/valueflows/resource/issues/39#issuecomment-239349202
* for **each resource needed on input** we should have possibility to cast an intent, which takes us towards [The evolution of intents to commitments to claims to economic events](https://github.com/valueflows/exchange/issues/23) but to avoid jumping into *CfA* we just take case where someone will donate needed resource (reasonable if we plan to do something charitable)
Above gives us chance to see how all the involved resources (especially *vf:WorkResource*, *vf:ServiceResource* and *vf:UsageResource*) relate to:
 1. Agents
 2. Processes
 3. Intents
 4. Transfers & Allocations
* besides having possibility to cast *vf:Request* for some resource needed in particular process, we should have possibility to cast intent for some resource of particular type needed in multiple planned processes.

**Comment by fosterlynn** [comment]
My understanding from today's meeting on scope of first release: 

Core process model for vf:Transformation on observation layer, can delay plan layer, can delay vf:Transportation.  Do address vf:ServiceResource as output and input, vf:WorkResource, vf:UsageResource.

Unclear how far we can get with relationships with agents, but minimally the agents clearly involved in events will be included, such as the agent performing work.

Good use cases: the 3D printing one (core manufacturing process); a new one for repairing the printer (adding service, and workflow process).

Additions and corrections?

**Comment by elf-pavlik** [comment]
Let's try to stay away from agents and agency in this release and only focus on resources, processes and events connecting them into IPO chains.

**Comment by elf-pavlik** [comment]
I would propose to put very minimal set of requirements for this release:

* vf:MaterialResource (serial and non-serial ones)
* vf:ServiceResource - mostly to put emphasis on their *not storing* nature https://github.com/valueflows/resource/issues/15#issuecomment-241603861

* vf:Transformation - consume and create serial and non-serial resources, connecting it to *circular economy* so we need processes that can consume everything that previous processes created and create from it at least secondary raw materials.. #97 

* vf:IpoEvent (or whatever we end up calling it) - process related events which affect observable state of resources

Once we can agree on above 🎉 we can still try to include following in v0.1 or even better mark them as v0.2 deliverables

*vf:Transportation* - so far we can't move any resource even an inch, we can still ignore all the agents involved and focus on how this process changes physical location of serial and non-serial material resources

*vf:UsageResource* & *vf:WorkResource* - since they work as 'time based' stocks https://github.com/valueflows/resource/issues/51 we may have hard time to avoid wondering into plan layer, i think v0.2 could start going there slowly. Both of above have similar behavior as *vf:ServiceResource* - if they get created they can't get stored. For purpose of v0.1 we can mock out the work and usage with services. Let's say fablab organizes this 3d printing process in remote location, all the people need to transport themselves there and all the equipment provided by '3rd party' also needs to get transported. Input services 'bundle up' the work (or usage) together with consumed transportation services needed to provide '3d printer operating service' and '3d printer rental service'. Of course in v0.2 we will need to extend IPO chain we describe and capture those work and usage obscured by the service.

**Comment by elf-pavlik** [comment]
I changed name to 0.0 release, so that we can feel more relaxed about scope of that release and really focus on capturing what we can agree after 2 years of ongoing conversations 😄

**Comment by elf-pavlik** [comment]
To have example of *create* and *consume* for serial resources, I would like to include use case where we assembly and disassembly a bicycle. We have quite a bit of bicycle stories around so we can build nice narrative around it...

**Comment by fosterlynn** [comment]
that will be a good use case, one we haven't really dealt with (disassembly)

**Comment by fosterlynn** [comment]
The following is a pad done by @elf-pavlik and me as a step to scope the next set of work.  There is still some disagreement inside the pad, so don't worry if it is a little contradictory.  And it is incomplete, more a working document.   OK enough caveats....

# ValueFlows v0.0 internal milestone

## Focus

* Reproducting state of observable resources based on events log - extraterestials observe those resources with their sensors but can't understand anything about agreements between people, agency, intent or valuing
  * only IPO events since 'transfers' don't change state of resources
  * no notion of 'valuing' since it requries subjective ealuations of agents and doesn't fit independent observation
    * Q: does 'cite' event affect the observable state of cited knowledge resource? as non-blocking usage it doesn't even block other processes from using it
    * Q: what observated state of a resource 'work' and 'use' event affect? i can only think of the blocking aspect, so if tool or person engages with the process it/they can't engage with other processes during that time
* Include all observable IPO economic events whether they have an effect on resource quantity or not

    * Include Transportation - only address resources changing locations and don't reference any agents

* no aspect of agency - no control, no intent
* agents isolated from IPO
 * only foaf:Agent (foaf:Person & foaf:Group) + vf:Realationship
* no 'currency resources' - we just mark them as planned and possibly reference onging conversations
* equal emphasis on serial, lot and non-serial-lot resources, also substitutable and non-substitutable


### observed vf:IPOEvent

1. needs to reference particular resource, which may have some 'resource type' (event can NOT directly reference 'resource type') - resource can be logically defined from just type of resource to concrete inventoried resource with lots of detail [terms below need may need work on naming]
  * create - MaterialResource, ServiceResource, KnowledgeResource
  * consume - MaterialResource, ServiceResource
  * load - MaterialResource
  * unload - MaterialResource
  * accept - MaterialResource, KnowledgeResource
  * improve - MaterialResource, KnowledgeResource
  * cite - KnowledgeResource
  * use - UsageResource (unclear if we have use any more though, might be consume - or both)
  * work - WorkResource
  * out - MaterialResource
  * in - MaterialResource
2. unit used in description of the event needs to match unit of referenced resource (at least have convertable kind of the unit)
3. event references quantity acting on (which includes unit) - or has no quantity, as currently 'cite' events [i would like to delete the "no quantity" concept]


### units
* MaterialResource - mass, volume, each
* SerivceResource - each
* KnowledgeResource - each
* UsageResource - time
* WorkResource - time

### relation to '???Quantity' of event to 'vf:quantity'of resource (what implications '???Quantity' recorded on the resource has?)
* create - +
* consume - -
* load - - and + ?? (might be 2 events there?)
* unload - - and + ??
* accept - =
* improve - =
* cite - =
* use - =
* work - =
* out - -
* in - +

### Extensibility and Interoperability

RDF model allows to use any property on any class unless explicitly disallowed. One can extend VF model freely keeping in mind that other systems may not understand those exensions and silently ignore them

VF vocabularity will support linked open data (RDF based) and non-LOD ways of implementing interoperability.  We will try to document everything so that different target groups/technologies can use it productively.

**Comment by elf-pavlik** [comment]
Our conversation at some point started to gravitate around the quantitative values referenced from *vf:IPOEvent*. Just to capture my approach:

Different events have different *vf:action*, this event performs this action on referenced resource. Often actions have *impact* so I suggested *vf:impactQantity* at least for events which have impact on the resource. For events which have no impact on the resource we can try to clarify what the quantitative value which we want to reference from event means and possibly define one or more specific properties to reference all those quantitative values. In general properties **should not name expected value of value** we don't use them for 'strict typing'. Property name should capture the **meaning of relationship**, properties represent relationships (edges in the graph). For example instead calling property *agent* one better calls it *performer*, *provider*, *consumer* etc.

**Comment by fosterlynn** [comment]
>Often actions have impact so I suggested vf:impactQantity at least for events which have impact on the resource. For events which have no impact on the resource we can try to clarify what the quantitative value which we want to reference from event means and possibly define one or more specific properties to reference all those quantitative values. 

Actually I think it is important to have the same quantity name for all types of events.  Goal is to keep the vocab simple and clean.  The quantity serves a couple purposes also - for some types of resources, it will increment or decrement; but it always specifies the quantity that relates to the process in some way.

**Comment by fosterlynn** [comment]
@elf-pavlik I'm adding issues to the list in your first post here..... you can check them out at the end of your comment.
