### ISSUE TITLE
Meta project content

### ISSUE THREAD

**Issue by ahdinosaur** [valueflows/valueflows#43]
TODO list for myself, gonna submit these as separate PRs.
- [ ] LICENSE
- [ ] CONTRIBUTING.md (include [certificate of origin](https://github.com/nodejs/node/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-10) and [code of conduct](https://github.com/nodejs/node/blob/master/CONTRIBUTING.md#code-of-conduct))
- [x] AUTHORS (like [this](https://github.com/nodejs/node/blob/master/AUTHORS))
- [x] PRINCIPLES.md ([long-form description of principles](https://github.com/valueflows/valueflows/wiki/Principles-for-this-vocabulary), i prefer we have this in our main repo as opposed to wiki, so any changes are obvious)

also wrote some content in describing Value Flows to @Connoropolous, it's just refinement of existing content, might be worth a few more refinement cycles then merge into the README.md (or not):
- [x] merged

> > How would you most succinttly summarize the goals and intentions and short and long term plans of the valueflows space?
> 
> the purpose of Value Flows is define a common vocabulary so a lot of alternative economic software projects that are solving different pieces of the same puzzle are able to work together.
> 
> our principles for success are:
> 1. the vocabulary must support coordinating work between different people in different organizations using different software on different platforms using different human and programming languages.
> 2. the vocabulary must track the flows of resources (value) forwards and backwards.
> 3. the vocabulary must distribute income (rewards) according to peoples' contributions, regardless of where and when in the network those contributions occurred.
> 4. the vocabulary must be fractal: it must support high-level views of networks as well zooming in to lower and lower levels of detail.
> 5. the vocabulary must work at the recipe, planning, and accounting levels.
> 6. the vocabulary must work for alternative and traditional organizing shapes and economic relationships.
> 
> our next deliverable is to have separate API and UI apps playing with each others' people, groups, and relationships in-between by communicating through a [common vocabulary](https://github.com/valueflows/agent).
> 
> our long-term plan is to refine our common vocabularies, design a set of interoperable protocols for decentralized economic infrastructure, and deploy an ecosystem of interconnected apps to form the backbone of an alternative economic system that supports recipes, planning, and accounting for fractal networks.

**Comment by bhaugen** [comment]
I like all of that. "The system" in the restatement of principles is a little undefined. Might be sufficient to add in the previous sentence, "...to work together as an internetworked system". Or something like that.

The long form of the principles also includes 7 and 8. Can they also be shortened and included in a short form? Or are they sufficiently implied by 1 thru 6?

**Comment by ahdinosaur** [comment]
@bhaugen thanks for the feedback. changed "system" and "data format" to "vocabulary". i sped through the first pass and didn't really notice, now i've now edited it to merge 1 + 4 and 7 + 8, i think it's best to aim for the minimum words to communicate the general principles, keen for more feedback on that.

**Comment by bhaugen** [comment]
Like change to  "system" and "data format" to "vocabulary". @elf-pavlik - do you think long-form principle 8 is implied well enuf or shd it be spelled out?  (I do agree that a terse short-form is a good thing.)
